### ISSUE TITLE
Running sls invoke test results in: `the "path" argument must be of type string`

### ISSUE THREAD

**Issue by ldgarcia** [SC5/serverless-jest-plugin#19]
I am currently using `"serverless-jest-plugin": "^0.1.6"` and `"jest": "^22.2.2"`.

This is my config on `serverless.yml`:
````yml
custom:
  jest:
     roots:
      - '<rootDir>/tests'   
````

Running either `sls invoke test` or `sls invoke test --path tests` it outputs:
````bash
 FAIL  tests/customMessage.test.js
  ● Test suite failed to run

    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
      
      at assertPath (path.js:28:11)
      at Object.relative (path.js:1259:5)

 FAIL  tests/postConfirmation.test.js
  ● Test suite failed to run

    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
      
      at assertPath (path.js:28:11)
      at Object.relative (path.js:1259:5)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        0.483s
Ran all test suites.
````

**Comment by TakaGoto** [comment]
+1

**Comment by BWoodfork** [comment]
Also running into this issue

**Comment by hmshoaib** [comment]
Any fix for this?

**Comment by abhishek-nair** [comment]
Hi Any update on this?

**Comment by brafdlog** [comment]
+1

**Comment by dhm116** [comment]
This should be fixed now that Jest v23 is supported (I had been running into the same issues previously).
